version: "3.9"

services:
  fregepoc-redis:
    container_name: fregepoc-redis
    hostname: fregepoc-redis
    image: redis:latest
    networks:
      - fregepoc-main
    ports:
      - "16379:${DOCKER_REDIS_PORT}"
    profiles: ["services", "application"]
    restart: on-failure

  fregepoc-postgres:
    container_name: fregepoc-postgres
    hostname: fregepoc-postgres
    image: postgres:latest
    environment:
       - POSTGRES_USER=${DJANGO_DATABASE_USER}
       - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
       - POSTGRES_DB=${DJANGO_DATABASE_NAME}
    networks:
      - fregepoc-main
    ports:
      - "15432:${DOCKER_POSTGRES_PORT}"
    profiles: ["services", "application"]
    restart: on-failure
    volumes:
      - fregepoc_postgresql_data:/var/lib/postgresql/data

  fregepoc-backend: &backend
    container_name: fregepoc-backend
    image: fregepoc-backend-image
    build: ./backend
    hostname: backend
    command: >
      sh -c "python manage.py migrate --noinput
      && python manage.py initadmin
      && python manage.py runserver
      0.0.0.0:${DOCKER_BACKEND_PORT}"
    ports:
      - "${DOCKER_EGRESS_IP}:${DOCKER_BACKEND_PORT}:${DOCKER_BACKEND_PORT}"
    depends_on:
      - fregepoc-postgres
      - fregepoc-redis
    volumes:
      - ./backend:/app
      - fregepoc_tmp:${DJANGO_DOWNLOAD_PATH}
    networks:
      - fregepoc-main
    profiles: [ "application" ]
    restart: on-failure
    env_file:
      - .env

  fregepoc-prometheus:
    image: prom/prometheus
    container_name: fregepoc-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - fregepoc-main

  fregepoc-grafana:
    image: grafana/grafana
    container_name: fregepoc-grafana
    depends_on:
      - fregepoc-prometheus
    volumes:
      - fregepoc_grafana_storage:/var/lib/grafana
      - ./backend/fregepoc/observability/datasources:/etc/grafana/provisioning/datasources/
      - ./backend/fregepoc/observability/dashboards:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3000:3000
    networks:
      - fregepoc-main
    env_file:
      - .env

  fregepoc-celery-worker:
    <<: *backend
    container_name: fregepoc-celery-worker
    ports: []
    command: >
      sh -c "python3 manage.py celery_dev_autoreload"

  fregepoc-flower:
    <<: *backend
    container_name: fregepoc-flower
    command: celery -A fregepoc flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://fregepoc-redis
      CELERY_RESULT_BACKEND: redis://fregepoc-redis
    depends_on:
      - fregepoc-celery-worker
      - fregepoc-redis

networks:
  fregepoc-main:

volumes:
  fregepoc_postgresql_data:
  fregepoc_tmp:
  fregepoc_grafana_storage:
