apiVersion: 1

deleteDatasources:

datasources:
- name: Redis
  type: redis-datasource
  access: proxy
  orgId: 1
  isDefault: false
  version: 1
  url: redis://fregepoc-redis:6379
  jsonData:
    client: standalone
    poolSize: 5
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0
  editable: true
