apiVersion: 1

datasources:
- name: postgres
  type: postgres
  access: proxy
  url: fregepoc-postgres:5432
  password: admin
  user: frege
  database: dashboard
  basicAuth: false
  isDefault: true
  jsonData:
     sslmode: disable
  version: 1
  editable: true
